---
title: "Tarea 2: Personas desaparecidas en México."
author: 
        - "Emma Alicia Jimenez Sanchez - 320046155"
        - "Nancy Elena del Valle - 117001778"
        - "Leonardo Rafael Ortiz Cervantes - 320059362"
format: pdf
jupyter: python3
---

# Descripción del Dataset

## Carga de datos
El data set utilizado en este reporte corresponde al archivo data_secretariado.csv, este contiene información sobre las personas que han sido reportadas como desaparecidas en el país. 

Sus caracteristicas se describen a continuación:
```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
```
```{python}
DATA_RAW = "../data/raw/data_secretariado.csv"

df = pd.read_csv(DATA_RAW)
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])
```

Con las siguientes columnnas:
```{python}
print(df.columns)
```

Para analizar el periodo de fechas completo es necesario aislar los valores únicos para centrarnos solo en aquellos que tengan sentido. Más adelante veremos si es necesario eliminar o modificar estos valores para un análisis más preciso.
```{python}
dfDesaparicion = pd.to_datetime(df["FECHA_DESAPARICION"], dayfirst=True, errors='coerce')
dfRegistro = pd.to_datetime(df["FECHA_REGISTRO"], dayfirst=True, errors='coerce')

print("Las desapariciones van desde "+str(dfDesaparicion.min())+" hasta "+str(dfDesaparicion.max()))

print("Los registros van desde "+str(dfRegistro.min())+" hasta "+str(dfRegistro.max()))
```

Analizando los primeros registros del dataset, podemos observar que cada uno corresponde a un registro de los reportes de desaparición realizados en cada entidad.

```{python}
df.head()
```

# Medidad Descriptivas y Análisis Exploratorio de Datos (EDA)

## Diccionario de Datos

| Nombre | Descripción | Tipo Dato | Tipo Estadístico | 
| :--- | :--- | :--- | :--- | 
| **ID_VICTIMA** | Id único del registro | string | Nominal | 
| **ORIGEN_REPORTE** | Fiscalía o comision donde se origina el reporte | string | Nominal |
| **FECHA_NACIMIENTO** | Fecha de nacimiento de la persona reportada como desaparecida | string | Ordinal |
| **SEXO** | Sexo de la víctima (HOMBRE, CONFIDENCIAL, MUJER, INDERTERMINADO) | string | Nomial |
| **FECHA_DESAPARICION** | Fecha de desaparición de la víctima | string | Ordinal |
| **FECHA_REGISTRO** | Fecha de registro de la desaparición en la físcalía | string | Ordinal |
| **ESTATUS_VICTIMA** | Estatus de la persona desaparecida (DESPARECIDA, CONFIDENCIAL, NO LOCALIZADA) | string | Nominal |
| **CVE_ENT** | Clave entidad | int64 | Continua |
| **ENTIDAD** | Fecha del evento de desaparición | string | Nominal |
| **CVE_MUN** | Clave municipio | int64 | Continua |
| **MUNICIPIO** | Fecha del evento de desaparición | string | Nominal |

## Aplicación de CRISP-DM al dataset asignado
### Comprensión del Negocio
El objetivo de este análisis es identificar patrones y características relevantes en los registros de personas desaparecidas en México. Algunas preguntas clave incluyen:

- ¿En qué periodos se concentran más desapariciones?

- ¿Qué regiones presentan mayor incidencia?

- ¿Existen patrones en edad o sexo?

- ¿Cuál es la tasa de información confidencial por estado?

- ¿Cuál es el promedio de desapariciones por estado y de acuerdo al estatus?

En las secciones anteriores se ha desglosado un poco de la exploración inicial del data set, identificando los tipos de datos y las principales inconsistencias de tipos en columnas como las de fecha.

Así, al realizar una conteo de valores faltantes notamos que la mayoria se encuentra en las columnas correspondientes a las fechas. 
```{python}
df.isnull().sum()
```
Los porcentajes correspondientes a cada uno de estos se encuentran a continuación:
```{python}
(df.isnull().sum() / len(df)) * 100
```

Lo siguiente es identificar los valores almacenados de manera erronea:
```{python}
df.dtypes
```
La mayoria de las columnas aparece con el tipo **object** lo cual nos indica que puede ser una cadena, diccionario, listas o una mezcla de todo esto. Nos afectará principalmente al tratar de realizar operaciones con las fechas pues, como se vio antes, es necesario convertirlas a datetime para poder calcular la edad aproximada del sujeto.

Revisaremos aquellas columnas que deban tener valores constantes, como sexo, entidad y municipio para detectar valores extraños.

**SEXO**
```{python}
df['SEXO'].unique()
```
Se detectaron dos tipo de valores extraños: *Confidencial* e *Indeterminado*. Dentro de este dataset hay muchos valores marcados como confidenciales, sin embargo, el uso de *Indeterminado* puede referirse a un valor perdido como para personas desaparecidas que no caen en la binaridad de género.

**ESTATUS_VICTIMA**
```{python}
df['ESTATUS_VICTIMA'].unique()
```
Como se menciono antes se usa *Confidencial* para tratar valores reservados, pero notemos que si una persona esta *Desaparecida* implica que no se le ha localizado, por lo que es redundante tener dos valores categóricas diferentes que significan lo mismo.

**ENTIDAD**
```{python}
df['ENTIDAD'].unique()
```
En esta columna se coloca un *Se Desconoce* para los valores faltantes.

**MUNICIPIO**
```{python}
df['MUNICIPIO'].unique()
```
Vuelve a usarse la palabra *Confidencial* para aquellos datos reservados.

Lo siguiente lograr identificar la existencia de valores duplicados. Además del sexo, fecha de nacimiento y lugar de desaparición no tenemos ningún otro dato extra sobre las victimas, solo una columna *id*, la cual no se sabe si esta relacionada con otra base de datos que nos de datos más sensibles como el nombre de la persona o solo fue la forma de identificar cada uno de los registros dentro de este data set. 
```{python}
df['ID_VICTIMA'].unique()
```
Notemos que tenemos exactamente el mismo número de valores únicos en la columna *ID_VICTIMA* como columnas dentro de la tabla completa. Por la falta de datos que nos indiquen con presición la existencia de duplicados, supondremos que no los hay, de lo contrario podriamos eliminar casos que parecen ser el mismo pero que en realidad no lo son.

Por el análisis pequeño hecho en la primera parte de este reporte, ya sabemos que todas las columnas correspondientes a fechas presentan valores erroneos que no permiten la conversión al tipo *datetime* de manera automática. Revisamo cada una de las diferentes columnas para tener una clara comprensión de los errores:

**Fecha de Nacimiento**
```{python}
df['FECHA_NACIMIENTO'].value_counts().sort_index().head(20)
```
```{python}
df['FECHA_NACIMIENTO'].value_counts().sort_index().tail(20)
```
Notemos que en esta columna existen valores con años imposibles, pues nos habla de gente que nacio hace más de un siglo o de personas que ni siquiera han nacido.

**Fecha de Desaparición**
```{python}
df['FECHA_DESAPARICION'].value_counts().sort_index().head(20)
```
```{python}
df['FECHA_DESAPARICION'].value_counts().sort_index().tail(20)
```
Dentro de estos datos no se presenta ningún valor fuera de rango.

**Fecha de Reporte**
```{python}
df['FECHA_REGISTRO'].value_counts().sort_index().head(20)
```
```{python}
df['FECHA_REGISTRO'].value_counts().sort_index().tail(20)
```
Dentro de estos datos no se presenta ningún valor fuera de rango.

Así, con esta exploración podemos determinar que, aun cuando existe una mala calidad de datos con un gran número de valores erroneos o incompletos es posible hacer un tratamiento de los mismos para lograr realizar un análisis estadístico completo que nos permita responder las preguntas planteadas.

### Data Preparation
Para preparar los datos para el análisis, se aplicarán las siguientes técnicas:
**Conversión de fechas**
Dentro del archivo *normalizar.py* se encuentran las funciones necesarias para corregir los años irregulares dentro de la columna fecha de nacimiento, como la herramienta **pandas** permite tener años con menos de 4 digitos entonces lo dividimos en dos casos:

- Si el año solo tiene 2 digitos y es menor a 26, los dos ultimos digitos del año actual, entonces se le suma este valor a 2000. Si el mayor a 26 se suma al valor 1900.

- Si el año tiene 3 digitos entonces revisaremos sus valores inciales, si empieza con 19 se agregará un 0 al final para tener un número entre 1900 y 1990. Si empieza con 20 se hace exactamente lo mismo, pero ahora nos dara un valor entre 2000 y 2990. Si no cae en ninguno de estos dos casos se le suma 1000 al valor.

Después de este proceso se hace una verificación de la cota susperior de los años, verificando que no pasen de cierto año:

- Si resulta ser mayor a 2100 se toman los dos ultimos digitos y se reconstruye la fecha para que tenga sentido  dentro del siglo XX/XXI

- Si esta entre 2026 y 2100 le restamos 100 al valor.

En todos estos casos el resultado de aplicar las operaciones se vuelve el nuevo valor de año. Además, se verifico que para cada víctima la fecha de nacimiento tuviera sentido, tomando como ancla la fecha de desaparición o de registro y restandole 100 para obtener el aproximado de nacimiento. Si no es posible validar la coherencia el valor se marca como nulo.

Finalmente después de todo este proceso, se convierten todos los datos actualizados al tipo *datetime* y si existe algún error se marca como nulo.

**Manejo de Duplicados**

Como se indico con anterioridad, por la falta de más información sobre las víctimas se considerará que dentro de este data set no existen duplicados. Pues de otra forma podriamos eliminar información importante para que una persona pueda volver con sus familiares.

**Limpieza de texto**

Dentro de las variables categóricas no se encontro ninguna necesidad de normalizar el texto, pues no habian errores ortográficos o de puntuación que nos dieran categorías extras repetidas. 

A pesar de que en la primera parte de este reporte se menciono que la columna **Estatus** contaba con dos valores similares *desaparecida* y *no localizada*, al no contar con mayor información sobre estas categorías, no pudimos determinar si existía o no una diferencia entre ambas, optando por no procedes con este cambio.

**Manejo de valores faltantes**

En el archovo *input_data.py* se imputan los valores para aquellas columnas que presentan valores nulos:

- *Fecha de Nacimiento:* Se calcula la media de esta columna y se remplaza con este a los valores faltantes.

- *Fecha de Desaparición:* Calculamos la mediana por estado y remplazamos con los resultados a los valores faltantes. Si al terminar este proceso siguen habiendo nulos, se remplazan por la mediana global.

- *Fecha de Registro:* Se iguala a la de desaparición.

### Modelling
En este caso, el objetivo es realizar un análisis descriptivo y exploratorio, por lo que no se aplicarán modelos predictivos. Sin embargo, dependiendo de los hallazgos, se podrían aplicar técnicas de clustering para identificar grupos de casos similares o modelos de clasificación para predecir el estado de las víctimas.

# Cálculo de medidas con visualizaciones e interpretación
## Medidas de localización
## Medidas de variabilidad
## Medidas de heterogeneidad
## Medidas de concentración

# Correlación
Se generó la matriz de correlación considerando únicamente las variables numéricas del dataset, con el objetivo de identificar relaciones lineales entre ellas. 

```{python}
DATA_IMPUTED = "../data/input_data/data_imputed.csv"

dfImputed = pd.read_csv(DATA_IMPUTED)

corr = dfImputed.corr(numeric_only=True)

plt.figure()

sns.heatmap(corr, annot=True)

plt.title("Matriz de correlación")
plt.show()
```
**Correlaciones Fuertes**
```{python}
corr_unstack = corr.unstack()

# Quitar correlaciones consigo mismo
corr_unstack = corr_unstack[corr_unstack != 1]

# Ordenar
corr_ordenadas = corr_unstack.sort_values(ascending=False)

corr_ordenadas.head(10)
```
Notemos que alcanzan valores cercanos a 1, sugiriendo que estas variables se encuentran altamente relacionadas posiblemente porque muchas representan información categórica transformada a valores numéricos.

La variable que predomina en estas relaciones es *ESTATUS_MAP*, la cual corresponde a la representación numérica de la variable categórica *ESTATUS*. La alta correlación observada con el resto de variables puede explicarse ya que factores como la fecha de desaparición y la fecha de registro influyen en la rapidez con la que se activan los mecanismos de búsqueda.

**Correlaciones Débiles**
```{python}
corr_ordenadas.tail(10)
```
De entre estas variables la que más se repite es *CVE_ENT* que corresponde a una clave geográfica de la entidad federativa, por lo que tiene sentido que su codificación numérica no implique ninguna relación con el resto.

# Conclusiones
## Limitaciones del Análisis
Una de las mayores límitaciones que presenta este análisis es la poca información que se sabe de los casos para lograr determinar con certeza si existen duplicados, pues estos podrian analizar modelos posteriores que se realicen sobre este data set.

Además, la presencia de datos *Confidenciales* nos impide llegar a análisis profundos de los casos, limitandonos tanto en aspectos de fechas, como de estados, así como conocer si existen personas que ya han sido localizadas.

## Hallazgos
Entre los hallazgos que encontramos en este dataset se encuentran:

1. Dado que se cuentan con varios datos *Confidenciales* dentro de las columnas podemos obtener la tasa de los mismos por estado de la siguiente manera:

```{python}
#Detectamos valores confidenciales en todo el dataset
mask_conf = dfImputed.apply(lambda row: row.astype(str).str.contains("CONFIDENCIAL", case=False, na=False).any(), axis=1)

dfImputed["TIENE_CONFIDENCIAL"] = mask_conf

tasa_conf = dfImputed.groupby("ENTIDAD")["TIENE_CONFIDENCIAL"].mean() * 100
tasa_conf.sort_values(ascending=False)
```
```{python}
tasa_conf.plot(kind="bar")
plt.title("Porcentaje de registros con información confidencial por entidad")
plt.ylabel("%")
plt.show()
```
Donde observamos que la entidad con mayor tasa de confidencialidad es Jalisco y la de menor Chihuahua.

2. Para obtener las desapariciones por estado podemos realizar un simple conteo:
```{python}
dfImputed["ENTIDAD"].value_counts()
```
Sin embargo, gracias a que se realizo un proceso exahustivo para la correcta normalización de fechas podemos obtener también el promedio de las desapariciones por año dentro de cada entidad:
```{python}
#Obtenemos año
fechas = pd.to_datetime(dfImputed["FECHA_DESAPARICION"], errors="coerce")
dfImputed["AÑO"] = fechas.dt.year

conteo = dfImputed.groupby(["ENTIDAD", "AÑO"]).size()

promedio_estado = conteo.groupby("ENTIDAD").mean()
promedio_estado.sort_values(ascending=False)
```

```{python}
promedio_estado.plot(kind="bar")
plt.title("Promedio de desapariciones por entidad por año")
plt.ylabel("Promedio")
plt.show()
```
Donde el que presenta mayor promedio de desapariciones es Tamaulipas y el de menor es Tlaxcala.

3. A su vez también podemos obtener la edad promedio de todas las personas registradas como desaparecidas:
```{python}
dfImputed["FECHA_NACIMIENTO"] = pd.to_datetime(dfImputed["FECHA_NACIMIENTO"], errors="coerce")
dfImputed["FECHA_DESAPARICION"] = pd.to_datetime(dfImputed["FECHA_DESAPARICION"], errors="coerce")

dfImputed["EDAD"] = (dfImputed["FECHA_DESAPARICION"] - dfImputed["FECHA_NACIMIENTO"]).dt.days / 365

promedioEdad = dfImputed["EDAD"].mean()

print(f"La edad promedio de desaparición es {promedioEdad:.2f}")
```

4. A su vez, podemos obtener este promedio por cada una de las entidades:
```{python}
dfImputed.groupby("ENTIDAD")["EDAD"].mean()
```

5. Dado los periodos de tiempo que abarca este data set, podemos calcular la tasa de desapariciones por diferentes periodos de tiempo. Primero lo abordaremos por años:
```{python}
fechas = pd.to_datetime(dfImputed["FECHA_DESAPARICION"], errors="coerce") 
dfImputed["AÑO"] = fechas.dt.year

desapariciones_por_año = dfImputed["AÑO"].value_counts().sort_index()

desapariciones_por_año
```

```{python}
desapariciones_por_año.plot(kind="line")
plt.title("Desapariciones por año")
plt.ylabel("Número de casos")
plt.show()
```
Notemos que el número de desapariciones es bastante bajo antes de la decada de los 2010's pero tiene sus primeros picos altos durante esta decada e inicios de los 2020.

6. El anterior análisis puede abordarse también por mes de la siguiente manera:
```{python}
dfImputed["MES"] = fechas.dt.month

desapariciones_por_mes = dfImputed["MES"].value_counts().sort_index()
desapariciones_por_mes
```
```{python}
desapariciones_por_mes.plot(kind="bar")
plt.title("Desapariciones por mes")
plt.ylabel("Número de casos")
plt.show()
```
El mes donde más numero de gente se reporta como desaparecida es Enero y en el que menor número de casos hay Octubre.

7. Y el realizar un análisis tanto por año como por mes nos arroja las siguientes observaciones:
```{python}
dfImputed["AÑO_MES"] = fechas.dt.to_period("M")

periodos = dfImputed["AÑO_MES"].value_counts().sort_index()
periodos
```

```{python}
periodos.plot(kind="line")
plt.title("Desapariciones por periodo (año-mes)")
plt.ylabel("Casos")
plt.show()
```
Aunque la tabla nos da la información compacta de todos los datos, al ordenar podemos obtener el año junto con el mes de los mayores reportes siendo este Enero del 2016.
```{python}
periodos.sort_values(ascending=False).head(10)
```
Y si obtenemos los últimos valores de este orden, veremos que los años con el menor número de reportes son alrededor de los años 60's y 70's.
```{python}
periodos.sort_values(ascending=False).tail(10)
``` 


